### ISSUE TITLE
Automated Jasmine Tests

### ISSUE THREAD

**Issue by sr229** [ClarityMoe/Sagiri#1]

**Comment by Ovyerus** [comment]
How would this be better than the current tests?

**Comment by sr229** [comment]
we use this for owo.js, they're actual unit tests

**Comment by Ovyerus** [comment]
A whole lib isnt really needed for two small, simple functions which don't need any other interaction

**Comment by sr229** [comment]
it already does the job of making these tests run in order automaticaly in a easier and non-uglier way, check how I did it on [owo.js](https://github.com/whats-this/owo.js)

**Comment by Ovyerus** [comment]
we can do that ourselves easily without needing a phat lib that has a lot of excess crap we don't need

**Comment by sr229** [comment]
Jasmine is a minimal lib, it's development purposes only

why would you fuckign use a test engine for production unless you're in a coma

**Comment by Ovyerus** [comment]
its late, and i have some hate for stupidly large libs which seem to overcomplicate things, as well as unit tests in general /shrug

who's not to say I'm in a comma
