### ISSUE TITLE
Fix "TODO" issue in lib/Sagiri.js

### ISSUE THREAD

**Issue by sr229** [ClarityMoe/Sagiri#4]
TODO found

https://codeclimate.com/github/ClarityMoe/Sagiri/lib/Sagiri.js#issue_59cb80721ab0340001000017

**Comment by sr229** [comment]
ovypls

**Comment by Ovyerus** [comment]
![shrug](https://owo.whats-th.is/e5e078.png)

**Comment by sr229** [comment]
o
