### ISSUE TITLE
Add more indexes

### ISSUE THREAD

**Issue by sr229** [ClarityMoe/Sagiri#6]
We probably need to find more indexes for the wrapper since we might encounter users reporting the "Unknown Index" errors.

- [ ] add possible missing indexes (index 0, index 1 , index 2, etc.)

**Comment by sr229** [comment]
Can we do some indexing on how many indexes does suaceNao search for potential images?

**Comment by Ovyerus** [comment]
What?

**Comment by Ovyerus** [comment]
49427f7 added a bunch of indexes and index aliases. This should cover all the indexes in the [range provided by SauceNAO](http://saucenao.com/status.html). Closing.
